#!/bin/bash

clear

echo ========== Setup
make clean

echo -e "\n========== Should compile everything, link and run tests"
make

echo -e "\n========== Should only recompile objects that depend on RandomAI.hpp, link and run tests"
touch include/AI/RandomAI/RandomAI.hpp
make
