#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinclude
CFLAGS = -g -std=c++11
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_TEST = $(INC)
CFLAGS_TEST = $(CFLAGS)
RESINC_TEST = $(RESINC)
RCFLAGS_TEST = $(RCFLAGS)
LIBDIR_TEST = $(LIBDIR)
LIB_TEST = $(LIB)lib/UnitTest++/Linux/libUnitTest++.a
LDFLAGS_TEST = $(LDFLAGS)
OBJDIR_TEST = obj
DEP_TEST = 
OUT_TEST = bin/Test/Test

INC_DARWINTICTACTOE = $(INC)
CFLAGS_DARWINTICTACTOE = $(CFLAGS)
RESINC_DARWINTICTACTOE = $(RESINC)
RCFLAGS_DARWINTICTACTOE = $(RCFLAGS)
LIBDIR_DARWINTICTACTOE = $(LIBDIR)
LIB_DARWINTICTACTOE = $(LIB)
LDFLAGS_DARWINTICTACTOE = $(LDFLAGS)
OBJDIR_DARWINTICTACTOE = obj
DEP_DARWINTICTACTOE = 
OUT_DARWINTICTACTOE = bin/DarwinTicTacToe/DarwinTicTacToe

INC_TICTACTOE = $(INC)
CFLAGS_TICTACTOE = $(CFLAGS)
RESINC_TICTACTOE = $(RESINC)
RCFLAGS_TICTACTOE = $(RCFLAGS)
LIBDIR_TICTACTOE = $(LIBDIR)
LIB_TICTACTOE = $(LIB)
LDFLAGS_TICTACTOE = $(LDFLAGS)
OBJDIR_TICTACTOE = obj
DEP_TICTACTOE = 
OUT_TICTACTOE = bin/TicTacToe/TicTacToe

OBJ_TEST = $(OBJDIR_TEST)/test/CerealTest.o $(OBJDIR_TEST)/source/StrongAI/AI/RandomAI/RandomAI.o $(OBJDIR_TEST)/test/CaseBasedAITest.o $(OBJDIR_TEST)/test/DarwinAITest.o $(OBJDIR_TEST)/test/GeneralAITest.o $(OBJDIR_TEST)/test/HumanAITest.o $(OBJDIR_TEST)/test/NeuralNetAITest.o $(OBJDIR_TEST)/test/RandomAITest.o $(OBJDIR_TEST)/test/SanityTest.o $(OBJDIR_TEST)/test/main.o $(OBJDIR_TEST)/source/StrongAI/AI/NeuralNetAI/NeuralNetAI.o $(OBJDIR_TEST)/source/StrongAI/AI/HumanAI/HumanAI.o $(OBJDIR_TEST)/source/StrongAI/AI/GeneralAI/GeneralAI.o $(OBJDIR_TEST)/source/StrongAI/AI/DarwinAI/DarwinAI.o $(OBJDIR_TEST)/source/StrongAI/AI/CaseBasedAI/CaseBasedAI.o

OBJ_DARWINTICTACTOE = $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/RandomAI/RandomAI.o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe/TicTacToe.o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe/TicTacToeHuman.o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe/main.o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/NeuralNetAI/NeuralNetAI.o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/HumanAI/HumanAI.o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/GeneralAI/GeneralAI.o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/DarwinAI/DarwinAI.o

OBJ_TICTACTOE = $(OBJDIR_TICTACTOE)/source/StrongAI/World/TicTacToe/TicTacToeHuman.o $(OBJDIR_TICTACTOE)/source/StrongAI/World/TicTacToe/main.o $(OBJDIR_TICTACTOE)/source/StrongAI/AI/HumanAI/HumanAI.o $(OBJDIR_TICTACTOE)/source/StrongAI/AI/GeneralAI/GeneralAI.o $(OBJDIR_TICTACTOE)/source/StrongAI/AI/CaseBasedAI/CaseBasedAI.o

all: test darwintictactoe tictactoe

clean: clean_test clean_darwintictactoe clean_tictactoe

before_test: 
	test -d bin/Test || mkdir -p bin/Test
	test -d $(OBJDIR_TEST)/test || mkdir -p $(OBJDIR_TEST)/test
	test -d $(OBJDIR_TEST)/source/StrongAI/AI/RandomAI || mkdir -p $(OBJDIR_TEST)/source/StrongAI/AI/RandomAI
	test -d $(OBJDIR_TEST)/source/StrongAI/AI/NeuralNetAI || mkdir -p $(OBJDIR_TEST)/source/StrongAI/AI/NeuralNetAI
	test -d $(OBJDIR_TEST)/source/StrongAI/AI/HumanAI || mkdir -p $(OBJDIR_TEST)/source/StrongAI/AI/HumanAI
	test -d $(OBJDIR_TEST)/source/StrongAI/AI/GeneralAI || mkdir -p $(OBJDIR_TEST)/source/StrongAI/AI/GeneralAI
	test -d $(OBJDIR_TEST)/source/StrongAI/AI/DarwinAI || mkdir -p $(OBJDIR_TEST)/source/StrongAI/AI/DarwinAI
	test -d $(OBJDIR_TEST)/source/StrongAI/AI/CaseBasedAI || mkdir -p $(OBJDIR_TEST)/source/StrongAI/AI/CaseBasedAI

after_test: 
	./bin/Test/Test

test: before_test out_test after_test

out_test: before_test $(OBJ_TEST) $(DEP_TEST)
	$(LD) $(LIBDIR_TEST) -o $(OUT_TEST) $(OBJ_TEST)  $(LDFLAGS_TEST) $(LIB_TEST)

$(OBJDIR_TEST)/test/CerealTest.o: test/CerealTest.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/CerealTest.cpp -o $(OBJDIR_TEST)/test/CerealTest.o

$(OBJDIR_TEST)/source/StrongAI/AI/RandomAI/RandomAI.o: source/StrongAI/AI/RandomAI/RandomAI.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c source/StrongAI/AI/RandomAI/RandomAI.cpp -o $(OBJDIR_TEST)/source/StrongAI/AI/RandomAI/RandomAI.o

$(OBJDIR_TEST)/test/CaseBasedAITest.o: test/CaseBasedAITest.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/CaseBasedAITest.cpp -o $(OBJDIR_TEST)/test/CaseBasedAITest.o

$(OBJDIR_TEST)/test/DarwinAITest.o: test/DarwinAITest.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/DarwinAITest.cpp -o $(OBJDIR_TEST)/test/DarwinAITest.o

$(OBJDIR_TEST)/test/GeneralAITest.o: test/GeneralAITest.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/GeneralAITest.cpp -o $(OBJDIR_TEST)/test/GeneralAITest.o

$(OBJDIR_TEST)/test/HumanAITest.o: test/HumanAITest.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/HumanAITest.cpp -o $(OBJDIR_TEST)/test/HumanAITest.o

$(OBJDIR_TEST)/test/NeuralNetAITest.o: test/NeuralNetAITest.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/NeuralNetAITest.cpp -o $(OBJDIR_TEST)/test/NeuralNetAITest.o

$(OBJDIR_TEST)/test/RandomAITest.o: test/RandomAITest.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/RandomAITest.cpp -o $(OBJDIR_TEST)/test/RandomAITest.o

$(OBJDIR_TEST)/test/SanityTest.o: test/SanityTest.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/SanityTest.cpp -o $(OBJDIR_TEST)/test/SanityTest.o

$(OBJDIR_TEST)/test/main.o: test/main.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c test/main.cpp -o $(OBJDIR_TEST)/test/main.o

$(OBJDIR_TEST)/source/StrongAI/AI/NeuralNetAI/NeuralNetAI.o: source/StrongAI/AI/NeuralNetAI/NeuralNetAI.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c source/StrongAI/AI/NeuralNetAI/NeuralNetAI.cpp -o $(OBJDIR_TEST)/source/StrongAI/AI/NeuralNetAI/NeuralNetAI.o

$(OBJDIR_TEST)/source/StrongAI/AI/HumanAI/HumanAI.o: source/StrongAI/AI/HumanAI/HumanAI.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c source/StrongAI/AI/HumanAI/HumanAI.cpp -o $(OBJDIR_TEST)/source/StrongAI/AI/HumanAI/HumanAI.o

$(OBJDIR_TEST)/source/StrongAI/AI/GeneralAI/GeneralAI.o: source/StrongAI/AI/GeneralAI/GeneralAI.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c source/StrongAI/AI/GeneralAI/GeneralAI.cpp -o $(OBJDIR_TEST)/source/StrongAI/AI/GeneralAI/GeneralAI.o

$(OBJDIR_TEST)/source/StrongAI/AI/DarwinAI/DarwinAI.o: source/StrongAI/AI/DarwinAI/DarwinAI.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c source/StrongAI/AI/DarwinAI/DarwinAI.cpp -o $(OBJDIR_TEST)/source/StrongAI/AI/DarwinAI/DarwinAI.o

$(OBJDIR_TEST)/source/StrongAI/AI/CaseBasedAI/CaseBasedAI.o: source/StrongAI/AI/CaseBasedAI/CaseBasedAI.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c source/StrongAI/AI/CaseBasedAI/CaseBasedAI.cpp -o $(OBJDIR_TEST)/source/StrongAI/AI/CaseBasedAI/CaseBasedAI.o

clean_test: 
	rm -f $(OBJ_TEST) $(OUT_TEST)
	rm -rf bin/Test
	rm -rf $(OBJDIR_TEST)/test
	rm -rf $(OBJDIR_TEST)/source/StrongAI/AI/RandomAI
	rm -rf $(OBJDIR_TEST)/source/StrongAI/AI/NeuralNetAI
	rm -rf $(OBJDIR_TEST)/source/StrongAI/AI/HumanAI
	rm -rf $(OBJDIR_TEST)/source/StrongAI/AI/GeneralAI
	rm -rf $(OBJDIR_TEST)/source/StrongAI/AI/DarwinAI
	rm -rf $(OBJDIR_TEST)/source/StrongAI/AI/CaseBasedAI

before_darwintictactoe: 
	test -d bin/DarwinTicTacToe || mkdir -p bin/DarwinTicTacToe
	test -d $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/RandomAI || mkdir -p $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/RandomAI
	test -d $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe || mkdir -p $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe
	test -d $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/NeuralNetAI || mkdir -p $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/NeuralNetAI
	test -d $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/HumanAI || mkdir -p $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/HumanAI
	test -d $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/GeneralAI || mkdir -p $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/GeneralAI
	test -d $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/DarwinAI || mkdir -p $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/DarwinAI

after_darwintictactoe: 

darwintictactoe: before_darwintictactoe out_darwintictactoe after_darwintictactoe

out_darwintictactoe: before_darwintictactoe $(OBJ_DARWINTICTACTOE) $(DEP_DARWINTICTACTOE)
	$(LD) $(LIBDIR_DARWINTICTACTOE) -o $(OUT_DARWINTICTACTOE) $(OBJ_DARWINTICTACTOE)  $(LDFLAGS_DARWINTICTACTOE) $(LIB_DARWINTICTACTOE)

$(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/RandomAI/RandomAI.o: source/StrongAI/AI/RandomAI/RandomAI.cpp
	$(CXX) $(CFLAGS_DARWINTICTACTOE) $(INC_DARWINTICTACTOE) -c source/StrongAI/AI/RandomAI/RandomAI.cpp -o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/RandomAI/RandomAI.o

$(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe/TicTacToe.o: source/StrongAI/World/DarwinTicTacToe/TicTacToe.cpp
	$(CXX) $(CFLAGS_DARWINTICTACTOE) $(INC_DARWINTICTACTOE) -c source/StrongAI/World/DarwinTicTacToe/TicTacToe.cpp -o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe/TicTacToe.o

$(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe/TicTacToeHuman.o: source/StrongAI/World/DarwinTicTacToe/TicTacToeHuman.cpp
	$(CXX) $(CFLAGS_DARWINTICTACTOE) $(INC_DARWINTICTACTOE) -c source/StrongAI/World/DarwinTicTacToe/TicTacToeHuman.cpp -o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe/TicTacToeHuman.o

$(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe/main.o: source/StrongAI/World/DarwinTicTacToe/main.cpp
	$(CXX) $(CFLAGS_DARWINTICTACTOE) $(INC_DARWINTICTACTOE) -c source/StrongAI/World/DarwinTicTacToe/main.cpp -o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe/main.o

$(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/NeuralNetAI/NeuralNetAI.o: source/StrongAI/AI/NeuralNetAI/NeuralNetAI.cpp
	$(CXX) $(CFLAGS_DARWINTICTACTOE) $(INC_DARWINTICTACTOE) -c source/StrongAI/AI/NeuralNetAI/NeuralNetAI.cpp -o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/NeuralNetAI/NeuralNetAI.o

$(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/HumanAI/HumanAI.o: source/StrongAI/AI/HumanAI/HumanAI.cpp
	$(CXX) $(CFLAGS_DARWINTICTACTOE) $(INC_DARWINTICTACTOE) -c source/StrongAI/AI/HumanAI/HumanAI.cpp -o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/HumanAI/HumanAI.o

$(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/GeneralAI/GeneralAI.o: source/StrongAI/AI/GeneralAI/GeneralAI.cpp
	$(CXX) $(CFLAGS_DARWINTICTACTOE) $(INC_DARWINTICTACTOE) -c source/StrongAI/AI/GeneralAI/GeneralAI.cpp -o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/GeneralAI/GeneralAI.o

$(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/DarwinAI/DarwinAI.o: source/StrongAI/AI/DarwinAI/DarwinAI.cpp
	$(CXX) $(CFLAGS_DARWINTICTACTOE) $(INC_DARWINTICTACTOE) -c source/StrongAI/AI/DarwinAI/DarwinAI.cpp -o $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/DarwinAI/DarwinAI.o

clean_darwintictactoe: 
	rm -f $(OBJ_DARWINTICTACTOE) $(OUT_DARWINTICTACTOE)
	rm -rf bin/DarwinTicTacToe
	rm -rf $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/RandomAI
	rm -rf $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/World/DarwinTicTacToe
	rm -rf $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/NeuralNetAI
	rm -rf $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/HumanAI
	rm -rf $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/GeneralAI
	rm -rf $(OBJDIR_DARWINTICTACTOE)/source/StrongAI/AI/DarwinAI

before_tictactoe: 
	test -d bin/TicTacToe || mkdir -p bin/TicTacToe
	test -d $(OBJDIR_TICTACTOE)/source/StrongAI/World/TicTacToe || mkdir -p $(OBJDIR_TICTACTOE)/source/StrongAI/World/TicTacToe
	test -d $(OBJDIR_TICTACTOE)/source/StrongAI/AI/HumanAI || mkdir -p $(OBJDIR_TICTACTOE)/source/StrongAI/AI/HumanAI
	test -d $(OBJDIR_TICTACTOE)/source/StrongAI/AI/GeneralAI || mkdir -p $(OBJDIR_TICTACTOE)/source/StrongAI/AI/GeneralAI
	test -d $(OBJDIR_TICTACTOE)/source/StrongAI/AI/CaseBasedAI || mkdir -p $(OBJDIR_TICTACTOE)/source/StrongAI/AI/CaseBasedAI

after_tictactoe: 

tictactoe: before_tictactoe out_tictactoe after_tictactoe

out_tictactoe: before_tictactoe $(OBJ_TICTACTOE) $(DEP_TICTACTOE)
	$(LD) $(LIBDIR_TICTACTOE) -o $(OUT_TICTACTOE) $(OBJ_TICTACTOE)  $(LDFLAGS_TICTACTOE) $(LIB_TICTACTOE)

$(OBJDIR_TICTACTOE)/source/StrongAI/World/TicTacToe/TicTacToeHuman.o: source/StrongAI/World/TicTacToe/TicTacToeHuman.cpp
	$(CXX) $(CFLAGS_TICTACTOE) $(INC_TICTACTOE) -c source/StrongAI/World/TicTacToe/TicTacToeHuman.cpp -o $(OBJDIR_TICTACTOE)/source/StrongAI/World/TicTacToe/TicTacToeHuman.o

$(OBJDIR_TICTACTOE)/source/StrongAI/World/TicTacToe/main.o: source/StrongAI/World/TicTacToe/main.cpp
	$(CXX) $(CFLAGS_TICTACTOE) $(INC_TICTACTOE) -c source/StrongAI/World/TicTacToe/main.cpp -o $(OBJDIR_TICTACTOE)/source/StrongAI/World/TicTacToe/main.o

$(OBJDIR_TICTACTOE)/source/StrongAI/AI/HumanAI/HumanAI.o: source/StrongAI/AI/HumanAI/HumanAI.cpp
	$(CXX) $(CFLAGS_TICTACTOE) $(INC_TICTACTOE) -c source/StrongAI/AI/HumanAI/HumanAI.cpp -o $(OBJDIR_TICTACTOE)/source/StrongAI/AI/HumanAI/HumanAI.o

$(OBJDIR_TICTACTOE)/source/StrongAI/AI/GeneralAI/GeneralAI.o: source/StrongAI/AI/GeneralAI/GeneralAI.cpp
	$(CXX) $(CFLAGS_TICTACTOE) $(INC_TICTACTOE) -c source/StrongAI/AI/GeneralAI/GeneralAI.cpp -o $(OBJDIR_TICTACTOE)/source/StrongAI/AI/GeneralAI/GeneralAI.o

$(OBJDIR_TICTACTOE)/source/StrongAI/AI/CaseBasedAI/CaseBasedAI.o: source/StrongAI/AI/CaseBasedAI/CaseBasedAI.cpp
	$(CXX) $(CFLAGS_TICTACTOE) $(INC_TICTACTOE) -c source/StrongAI/AI/CaseBasedAI/CaseBasedAI.cpp -o $(OBJDIR_TICTACTOE)/source/StrongAI/AI/CaseBasedAI/CaseBasedAI.o

clean_tictactoe: 
	rm -f $(OBJ_TICTACTOE) $(OUT_TICTACTOE)
	rm -rf bin/TicTacToe
	rm -rf $(OBJDIR_TICTACTOE)/source/StrongAI/World/TicTacToe
	rm -rf $(OBJDIR_TICTACTOE)/source/StrongAI/AI/HumanAI
	rm -rf $(OBJDIR_TICTACTOE)/source/StrongAI/AI/GeneralAI
	rm -rf $(OBJDIR_TICTACTOE)/source/StrongAI/AI/CaseBasedAI

.PHONY: before_test after_test clean_test before_darwintictactoe after_darwintictactoe clean_darwintictactoe before_tictactoe after_tictactoe clean_tictactoe

